### ISSUE TITLE
Is the closing date correct?

### ISSUE THREAD

**Issue by bast** [bosilca/MPIsurvey#1]
The README says "This survey will be closed by the end of February 2019" - however I learned about this survey end of March and it is still open (and I think it is good that it is still open).

**Comment by bosilca** [comment]
@bast I will update the README to reflect our decision to leave the survey open for now, basically until we figure out how to reach communities that are currently outside the reach of google forms (@ahori is actively working on this). Meanwhile, we will start dumping the data according to the extraction date.

**Comment by bosilca** [comment]
@ahori has updated the README.
